# India AQI Insights : A Data Analytics Study of Indian Cities (2022-2025)

## 1. Project Overview

Air pollution is one of the major environmental challenges affecting public health and quality of life.

This project analyzes Air Quality Index (AQI) data collected from multiple Indian cities between 2022 and 2025. The goal is to understand pollution trends, identify highly polluted cities, determine dominant pollutants, and evaluate overall air quality conditions.

## 2. Objectives

The objectives of this project are:

- Analyze AQI trends over time.
- Identify cities with the highest pollution levels.
- Determine the most frequently occurring pollutants.
- Examine the distribution of air quality categories.
- Prepare a clean dataset for dashboard development in Excel.

##  3. Dataset Overview
This dataset contains comprehensive records of air quality across various states and cities of India, including AQI values, pollutants, and air quality statuses over time.

Total Records: 235,785
Time Span: Multiple dates (latest: 30-April-2025)
- Coverage: 32 States and 291 cities
  
##### Features Explained
Column Name and	Description
- date :    Date of observation (DD-MM-YYYY format)
- state :	Indian state name
- area:	  City or locality where the reading was recorded
- number_of_monitoring_stations:	Number of stations in the area recording AQI
- prominent_pollutants: 	Dominant pollutant for that location on the given day (e.g., PM2.5, PM10, CO, NO2, O3)
- aqi_value:	Air Quality Index value (ranging from 0 to 500)
- air_quality_status:	AQI category (e.g., Good, Satisfactory, Moderate, Poor, Very Poor, Severe)
- unit: 	Description unit of AQI (textual, mostly constant)

## 4. Import Libraries

In [ ]:
import pandas as pd
import numpy as np

## 5. Data Loading and Understanding

In [115]:
# load the dataset
df = pd.read_csv(r"D:\project\my project dataset\aqi.csv")

In [116]:
df.head()

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status,unit,note
0,30-04-2025,Maharashtra,Amravati,2,PM10,78,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
1,30-04-2025,Bihar,Purnia,1,CO,56,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
2,30-04-2025,Madhya Pradesh,Katni,1,O3,98,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN
3,30-04-2025,Chhattisgarh,Tumidih,1,PM10,103,Moderate,number_of_monitoring_stations in Absolute Numb...,NaN
4,30-04-2025,Assam,Byrnihat,1,PM2.5,61,Satisfactory,number_of_monitoring_stations in Absolute Numb...,NaN

In [117]:
df.shape

(235785, 9)

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235785 entries, 0 to 235784
Data columns (total 9 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   date                           235785 non-null  object
 1   state                          235785 non-null  object
 2   area                           235785 non-null  object
 3   number_of_monitoring_stations  235785 non-null  int64
 4   prominent_pollutants           235785 non-null  object
 5   aqi_value                      235785 non-null  int64
 6   air_quality_status             235785 non-null  object
 7   unit                           235785 non-null  object
 8   note                           0 non-null       float64
dtypes: float64(1), int64(2), object(6)
memory usage: 16.2+ MB

In [119]:
df.describe()

       number_of_monitoring_stations      aqi_value  note
count                  235785.000000  235785.000000   0.0
mean                        1.870653     111.127294   NaN
std                         3.071575      71.447353   NaN
min                         1.000000       3.000000   NaN
25%                         1.000000      59.000000   NaN
50%                         1.000000      92.000000   NaN
75%                         1.000000     142.000000   NaN
max                        40.000000     500.000000   NaN

In [120]:
df.columns

Index(['date', 'state', 'area', 'number_of_monitoring_stations',
       'prominent_pollutants', 'aqi_value', 'air_quality_status', 'unit',
       'note'],
      dtype='object')

## 6. Data Cleaning

In [121]:
# keep required columns
df = df[
    [
        'date',
        'area',
        'prominent_pollutants',
        'aqi_value',
        'state'
    ]
]

In [122]:
# check and drop missing values
missing = df.isnull().sum()
print(missing)

date                    0
area                    0
prominent_pollutants    0
aqi_value               0
state                   0
dtype: int64

In [123]:
# date conversion (the data become a date time object now)
df['date'] = pd.to_datetime(df['date'])

C:\Users\micky\AppData\Local\Temp\ipykernel_16588\3453377953.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date'] = pd.to_datetime(df['date'])

#### Data Cleaning Observations
- Selected only the relevant columns required for AQI analysis:
Date, state, City (Area), Prominent Pollutant, AQI Value
- Checked for missing values in all selected columns. No missing values were found in the dataset.
- Converted the date column from string format to datetime format for time-based analysis.

## 7. Feature Engineering

In [124]:
# create Month-year (Extract only the month and year)
df['month_year'] = df['date'].dt.to_period('M')

In [125]:
# create Year (Extract only the year)
df['year'] = df['date'].dt.year

In [126]:
# Create Month Name
df['month'] = df['date'].dt.month_name()

In [127]:
df.shape

(235785, 8)

In [128]:
df.head()

,date,area,prominent_pollutants,aqi_value,state,month_year,year,month
0,2025-04-30,Amravati,PM10,78,Maharashtra,2025-04,2025,April
1,2025-04-30,Purnia,CO,56,Bihar,2025-04,2025,April
2,2025-04-30,Katni,O3,98,Madhya Pradesh,2025-04,2025,April
3,2025-04-30,Tumidih,PM10,103,Chhattisgarh,2025-04,2025,April
4,2025-04-30,Byrnihat,PM2.5,61,Assam,2025-04,2025,April



#### Feature Engineering Observations

* Created a **Month-Year** column for monthly trend analysis.
* Extracted **Year** from the date column for yearly analysis.
* Extracted **Month** from the date column to identify monthly patterns.

## 8. Exploratory Data Analysis

#### 8.1. AQI Trend

In [129]:
monthly_trend = (
    df.groupby('month_year')['aqi_value'].mean()
      .reset_index()
)
monthly_trend.head()

  month_year   aqi_value
0    2022-04  140.681279
1    2022-05  122.354040
2    2022-06  106.250000
3    2022-07   61.290134
4    2022-08   64.694450

#### 8.2. Top Polluted Cities

In [130]:
top_cities = (
    df.groupby('area')['aqi_value']
      .mean()
      .sort_values(ascending=False)
      .head(10)
)
top_cities.head()

area
Byrnihat          239.995427
Begusarai         206.680412
Delhi             206.416889
Greater Noida     201.601959
Sri Ganganagar    197.939351
Name: aqi_value, dtype: float64

#### 8.3. Pollutant Analysis

In [131]:
pollutants = (
    df['prominent_pollutants']
    .str.split(',')
    .explode()
    .str.strip()
)

pollutant_distribution = (
    pollutants
    .value_counts()
    .reset_index()
)

pollutant_distribution.columns = [
    'Pollutant',
    'Count'
]

pollutant_distribution.head()

  Pollutant   Count
0      PM10  135806
1     PM2.5   78030
2        O3   24951
3        CO   18148
4       NO2    6025

####  8.4. monthly (state & city-wise) AQI Analysis

In [132]:
monthly_aqi = (
    df.groupby(['month_year', 'state', 'area'])['aqi_value']
      .mean()
      .reset_index()
)

monthly_aqi.rename(columns={
    'area': 'City',
    'aqi_value': 'Avg_AQI',
    'state': 'State'
}, inplace=True)

monthly_aqi.head()

  month_year              State               City    Avg_AQI
0    2022-04     Andhra Pradesh          Amaravati  36.466667
1    2022-04     Andhra Pradesh  Rajamahendravaram  37.000000
2    2022-04     Andhra Pradesh           Tirupati  67.033333
3    2022-04     Andhra Pradesh      Visakhapatnam  78.068966
4    2022-04  Arunachal Pradesh         Naharlagun  62.666667

#### 8.5. State-wise AQI analysis

In [133]:
state_aqi = (
    df.groupby('state')['aqi_value']
      .mean()
      .reset_index()
)

state_aqi.rename(columns={
    'state': 'State',
    'aqi_value': 'Avg_AQI'
}, inplace=True)

state_aqi.sort_values(by='Avg_AQI',ascending=False,inplace=True)
state_aqi.head()

               State     Avg_AQI
7              Delhi  206.416889
12         Jharkhand  164.940361
10  Himachal Pradesh  160.257036
4              Bihar  157.158122
5         Chandigarh  141.561778

#### Key Insights

* Air quality levels showed noticeable variation across different months, indicating seasonal changes in pollution patterns.
* Byrnihat, Begusarai, and Delhi ranked among the most polluted cities based on average AQI values.
* PM10 and PM2.5 were the most frequently reported pollutants, highlighting particulate matter as a major contributor to air pollution.
* Significant differences in average AQI were observed across Indian states, indicating regional variations in air quality conditions.

## 9. Export for Excel Dashboard

In [134]:
with pd.ExcelWriter(r"D:\project\my project dataset\AQI_Dashboard_Data.xlsx") as writer:

    monthly_aqi.to_excel(
        writer,
        sheet_name="Monthly_AQI",
        index=False
    )

    state_aqi.to_excel(
        writer,
        sheet_name="State_AQI",
        index=False
    )

    pollutant_distribution.to_excel(
        writer,
        sheet_name="Pollutants",
        index=False
    )

## 10. Conclusion
This project analyzed air quality data from Indian cities to understand pollution trends and patterns.The dataset was cleaned, transformed, and analyzed using Python. Key insights related to AQI trends, polluted cities, pollutant frequency, and state-wise AQI data were generated. The processed datasets were prepared for the development of an interactive Excel dashboard to visualize key insights and support data-driven understanding of air quality conditions across India.